import '@/src/styles/globals.scss';
import {Metadata} from "next";
import ClientProvider from "@/modules/ClientProvider";
import React from "react";
import MainLayout from "@/components/Layout/MainLayout";

export const metadata: Metadata = {
    title: 'template',
    description: 'description template',
    icons: {
        icon: '/online-store.ico'
    }
};
export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <title>Online store</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/online-store.ico" />
            <link
                href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
                rel="stylesheet"
            />
        </head>
        <body>
        <MainLayout>
            <ClientProvider>
                {children}
            </ClientProvider>
        </MainLayout>
        </body>
        </html>
    )
}
